### PR TITLE
Correcting the spelling twerk.

### PR DESCRIPTION
**Pull request by mohitm15**
Pull Request for Issue #69  .

### Summary of Changes

Corrected the typo.

### Testing Instructions

Go to respective file.

### Documentation Changes Required
Code_of_conduct.md

### CODE REVIEW

**Comment by mohitm15** [comment]
@bahl24 Please Review

**Comment by bahl24** [comment]
This repo is only for page builder, for changes in joomla core files please make issues and PRs in main joomla cms repo.

**Comment by mohitm15** [comment]
> This repo is only for page builder, for changes in joomla core files please make issues and PRs in main joomla cms repo.

Can you direct me to that?

**Comment by bahl24** [comment]
> > This repo is only for page builder, for changes in joomla core files please make issues and PRs in main joomla cms repo.
> 
> Can you direct me to that?

https://github.com/joomla/joomla-cms/tree/4.0-dev

**Pull request closed without merging**
