### PR TITLE
Minor Menu bar fixes

### PR DESCRIPTION
**Pull request by ravisaxena23**
Pull Request for Issue #  Make side menu more attractive. .

### Summary of Changes
1. Changed menu bar color to #12324C. this color actually resembles our theme.
2. Changed Normal Scrollbar to customized scroll bar. That also looks good on our theme.
Screenshot (73)
3. Changed menu bar design on mobile a little bit. for better user experience.
### before
Screenshot (70)
### after
Screenshot (75)
4. When i was understanding the code encounter  some minor fixes such as missing " added that.
5. Tried to make code understandable in incompatible.html and in other files.
6. Added text in readme so that one can easily open project in windows .
### Testing Instructions
1. Can open Using Chrome or any browser.
2. Remember I'm a Noob(n shame accepting it) and trying to learn things please give me a feedback and what i can improve
### Expected result
1. customized scrollbar.
2. menu color change
3. changes on mobile view 
### Actual result
1. customized scrollbar.
2. menu color change
3. changes on mobile view 
### Documentation Changes Required
No, Done that only added how to start project in windows it was bit difficult(haha)
### future plan
1 I want to make menu bar and toolbar fixed. because when user scroll down he/she has to scroll back to top to logout or go to another menu. this will ### enhance user experience.
2 I didn't done that because I want permission to try that also it may change all frontend dashboard ui it will take time and permission
3 blocks or cards on dashboard can be improved i can try.

### request
1. please give me my flaw reports.
2. please give me a mail or anything by which i can communicate.

Thank you

### CODE REVIEW

**Comment by anuragteapot** [comment]
@ravisaxena23 This PR is not related to  #44  But, you have fixed something else. Keep this PR as it is. 


For #44 You need to open the new page builder of Joomla.

**Comment by ravisaxena23** [comment]
Thank you sir for precious time. And sorry for wrong PR i will improve.

**Comment by ravisaxena23** [comment]
Actually I want to ask ki how to open new page builder of Joomla!. Jb mai
local host pr new page builder search krta hu tb error ata h sir and when I
just open gsoc19_page-builder tb theme khulti h casopeia! Do I have to work
on casopeia? Nhi toh kha work krna h I'm unable to find please help me find
it specify the location to me.

**Comment by anuragteapot** [comment]
> Actually I want to ask ki how to open new page builder of Joomla!. Jb mai local host pr new page builder search krta hu tb error ata h sir and when I just open gsoc19_page-builder tb theme khulti h casopeia! Do I have to work on casopeia? Nhi toh kha work krna h I'm unable to find please help me find it specify the location to me.
> […](#)

@ravisaxena23 No problem. And try to write in English because here people from different country works.


Read this. https://docs.joomla.org/J4.x:Page_Builder

**Comment by ravisaxena23** [comment]
Good morning sir,

Can I work on making side bar responsive? Please let me know. Please check
my pull request.

Regards
Ravi nandan Saxena

**Pull request closed without merging**
